# MPark.Variant
#
# Copyright Michael Park, 2015-2017
#
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE.md or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp
os: linux
dist: xenial
sudo: false

branches:
  only:
    - benchmark

git:
  depth: 1

env:
  global:
    - secure: jL8hAVoa2B512uGeoh5DL2YXrAznfKPz3GbcaUPzR6mR2Izj2yHFihLLeHrEY8vUdadS8zbn2CwtWnmJjNz5kIT/RxESxJJtgVNruwo0u4piIfxVI/tTRObMXKaGrfquDAHS/hjAhQlPSNNr+89oFSBvSfNpAVECd/ERhhnjIugD+MFFzaxi26qvM6li9toxPNJIxBq9jHRuZzlpWez6d6RcTsaqr30BaCEuJhVcg7J4SiSL8xeW2sokAG65pZ/aig23cCSJkhazbMd7Cy/OFNjQrhc2PQ+E0c2xEwdwCNA8qTnsMrUeo9NXc+lozOf23LWD1EvZtcNNG5arPhSuGGYs90T1GdL2jqyS1E+1Xf0cOWqB4VMho7H+vV55SgZb+TYDrmB63YvgxcUKgsDRvPI9bBv3S3uxgktbE6gwnrfQirKowbscC07X3R1RJiI6hSkVNdrLnQF28BHMRlCpyhDejIWm4qHgOrWCN+I6hZtk+nsRuJF8sCSFPUWuzlG+/kSwaBwm/eEy+ZI66ufJamHUqC8bxa+6kINxtJTMN79ZnbIPwOvey9cfVfzwxefaStwpQbCJuZlMbuo4738HxUQpscxgv6LA5ZEMz8hlKO82cWDZSEDxSrUowueu1Az0u5tfzBUXaU5pZCnGdK6aMGHcTznaeUFebq8uhLR3uc0=

matrix:
  include:
    # ubuntu 16.04, gcc-5, ctor.fwd
    - env: VER=5 STD=11 BENCHMARK="ctor.fwd" LIBS="boost;eggs;mapbox;mpark"
      compiler: gcc
      addons: &gcc5 { apt: { packages: ["g++-5"], sources: ["ubuntu-toolchain-r-test"] } }
    # ubuntu 16.04, gcc-5, visit.1
    - env: VER=5 STD=11 BENCHMARK="visit.1" LIBS="boost;eggs;mapbox;mpark"
      compiler: gcc
      addons: *gcc5
    # ubuntu 16.04, gcc-5, visit.2.equal
    - env: VER=5 STD=11 BENCHMARK="visit.2.equal" LIBS="boost;eggs;mapbox;mpark"
      compiler: gcc
      addons: *gcc5
    # ubuntu 16.04, gcc-5, visit.2.mixed
    - env: VER=5 STD=11 BENCHMARK="visit.2.mixed" LIBS="boost;eggs;mapbox;mpark"
      compiler: gcc
      addons: *gcc5

    # ubuntu 16.04, gcc-6, ctor.fwd
    - env: VER=6 STD=14 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: gcc
      addons: &gcc6 { apt: { packages: ["g++-6"], sources: ["ubuntu-toolchain-r-test"] } }
    # ubuntu 16.04, gcc-6, visit.1
    - env: VER=6 STD=14 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: gcc
      addons: *gcc6
    # ubuntu 16.04, gcc-6, visit.2.equal
    - env: VER=6 STD=14 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: gcc
      addons: *gcc6
    # ubuntu 16.04, gcc-6, visit.2.mixed
    - env: VER=6 STD=14 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: gcc
      addons: *gcc6

    # ubuntu 16.04, gcc-7, ctor.fwd
    - env: VER=7 STD=17 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: gcc
      addons: &gcc7 { apt: { packages: ["g++-7"], sources: ["ubuntu-toolchain-r-test"] } }
    # ubuntu 16.04, gcc-7, visit.1
    - env: VER=7 STD=17 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: gcc
      addons: *gcc7
    # ubuntu 16.04, gcc-7, visit.2.equal
    - env: VER=7 STD=17 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: gcc
      addons: *gcc7
    # ubuntu 16.04, gcc-7, visit.2.mixed
    - env: VER=7 STD=17 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: gcc
      addons: *gcc7

    # ubuntu 16.04, gcc-8, ctor.fwd
    - env: VER=8 STD=17 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: gcc
      addons: &gcc8 { apt: { packages: ["g++-8"], sources: ["ubuntu-toolchain-r-test"] } }
    # ubuntu 16.04, gcc-8, visit.1
    - env: VER=8 STD=17 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: gcc
      addons: *gcc8
    # ubuntu 16.04, gcc-8, visit.2.equal
    - env: VER=8 STD=17 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: gcc
      addons: *gcc8
    # ubuntu 16.04, gcc-8, visit.2.mixed
    - env: VER=8 STD=17 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: gcc
      addons: *gcc8

    # ubuntu 16.04, clang-3.6, ctor.fwd
    - env: VER=3.6 STD=11 BENCHMARK="ctor.fwd" LIBS="boost;eggs;mapbox;mpark"
      compiler: clang
      addons: &clang36 { apt: { packages: ["clang-3.6"] } }
    # ubuntu 16.04, clang-3.6, visit.1
    - env: VER=3.6 STD=11 BENCHMARK="visit.1" LIBS="boost;eggs;mapbox;mpark"
      compiler: clang
      addons: *clang36
    # ubuntu 16.04, clang-3.6, visit.2.equal
    - env: VER=3.6 STD=11 BENCHMARK="visit.2.equal" LIBS="boost;eggs;mapbox;mpark"
      compiler: clang
      addons: *clang36
    # ubuntu 16.04, clang-3.6, visit.2.mixed
    - env: VER=3.6 STD=11 BENCHMARK="visit.2.mixed" LIBS="boost;eggs;mapbox;mpark"
      compiler: clang
      addons: *clang36

    # ubuntu 16.04, clang-3.7, ctor.fwd
    - env: VER=3.7 STD=11 BENCHMARK="ctor.fwd" LIBS="boost;eggs;mapbox;mpark"
      compiler: clang
      addons: &clang37 { apt: { packages: ["clang-3.7"] } }
    # ubuntu 16.04, clang-3.7, visit.1
    - env: VER=3.7 STD=11 BENCHMARK="visit.1" LIBS="boost;eggs;mapbox;mpark"
      compiler: clang
      addons: *clang37
    # ubuntu 16.04, clang-3.7, visit.2.equal
    - env: VER=3.7 STD=11 BENCHMARK="visit.2.equal" LIBS="boost;eggs;mapbox;mpark"
      compiler: clang
      addons: *clang37
    # ubuntu 16.04, clang-3.7, visit.2.mixed
    - env: VER=3.7 STD=11 BENCHMARK="visit.2.mixed" LIBS="boost;eggs;mapbox;mpark"
      compiler: clang
      addons: *clang37

    # ubuntu 16.04, clang-3.8, ctor.fwd
    - env: VER=3.8 STD=14 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: &clang38 { apt: { packages: ["clang-3.8"] } }
    # ubuntu 16.04, clang-3.8, visit.1
    - env: VER=3.8 STD=14 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang38
    # ubuntu 16.04, clang-3.8, visit.2.equal
    - env: VER=3.8 STD=14 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang38
    # ubuntu 16.04, clang-3.8, visit.2.mixed
    - env: VER=3.8 STD=14 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang38

    # ubuntu 16.04, clang-3.9, ctor.fwd
    - env: VER=3.9 STD=14 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: &clang39 { apt: { packages: ["clang-3.9"] } }
    # ubuntu 16.04, clang-3.9, visit.1
    - env: VER=3.9 STD=14 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang39
    # ubuntu 16.04, clang-3.9, visit.2.equal
    - env: VER=3.9 STD=14 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang39
    # ubuntu 16.04, clang-3.9, visit.2.mixed
    - env: VER=3.9 STD=14 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang39

    # ubuntu 16.04, clang-4.0, ctor.fwd
    - env: VER=4.0 STD=14 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: &clang40 { apt: { packages: ["clang-4.0"] } }
    # ubuntu 16.04, clang-4.0, visit.1
    - env: VER=4.0 STD=14 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang40
    # ubuntu 16.04, clang-4.0, visit.2.equal
    - env: VER=4.0 STD=14 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang40
    # ubuntu 16.04, clang-4.0, visit.2.mixed
    - env: VER=4.0 STD=14 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov"
      compiler: clang
      addons: *clang40

    # ubuntu 16.04, clang-5.0, ctor.fwd
    - env: VER=5.0 STD=17 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: &clang50 { apt: { packages: ["clang-5.0"] } }
    # ubuntu 16.04, clang-5.0, visit.1
    - env: VER=5.0 STD=17 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang50
    # ubuntu 16.04, clang-5.0, visit.2.equal
    - env: VER=5.0 STD=17 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang50
    # ubuntu 16.04, clang-5.0, visit.2.mixed
    - env: VER=5.0 STD=17 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang50

    # ubuntu 16.04, clang-6.0, ctor.fwd
    - env: VER=6.0 STD=17 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: &clang60 { apt: { packages: ["clang-6.0"] } }
    # ubuntu 16.04, clang-6.0, visit.1
    - env: VER=6.0 STD=17 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang60
    # ubuntu 16.04, clang-6.0, visit.2.equal
    - env: VER=6.0 STD=17 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang60
    # ubuntu 16.04, clang-6.0, visit.2.mixed
    - env: VER=6.0 STD=17 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang60

    # ubuntu 16.04, clang-7, ctor.fwd
    - env: VER=7 STD=17 BENCHMARK="ctor.fwd" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: &clang7 { apt: { packages: ["clang-7"], sources: ["llvm-toolchain-xenial-7"] } }
    # ubuntu 16.04, clang-7, visit.1
    - env: VER=7 STD=17 BENCHMARK="visit.1" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang7
    # ubuntu 16.04, clang-7, visit.2.equal
    - env: VER=7 STD=17 BENCHMARK="visit.2.equal" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang7
    # ubuntu 16.04, clang-7, visit.2.mixed
    - env: VER=7 STD=17 BENCHMARK="visit.2.mixed" LIBS="anthonyw;boost;eggs;juice;mapbox;mpark;pdimov;std"
      compiler: clang
      addons: *clang7

before_install:
  - CMAKE_OPTIONS="-DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=${STD} -DMPARK_VARIANT_INCLUDE_LIBRARIES=${LIBS}"
  # Directory for dependency installation.
  - DEPS="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS}
  # Install newer cmake.
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew upgrade cmake
    fi
  - cmake --version
  # Save the name of the compiler.
  - COMPILER=${CC}
  # Set the correct `CC` and `CXX` environment variables.
  - |
    if [ -n "${VER}" ]; then
      export CC="${CC}-${VER}"
      export CXX="${CXX}-${VER}"
    fi
  - ${CXX} --version
  # Install specific version of libc++.
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ] && [ "${COMPILER}" = "clang" ] && [ -n "${VER}" ]; then
      LLVM_VER=$(echo "$(${CXX} --version)" | grep -Po "clang version \K([0-9]\.[0-9]\.[0-9])")
      if [ "${LLVM_VER}" = "5.0.1" ]; then
        LLVM_VER="5.0.0"
      fi

      LLVM_URL="http://llvm.org/releases/${LLVM_VER}/llvm-${LLVM_VER}.src.tar.xz"
      LIBCXX_URL="http://llvm.org/releases/${LLVM_VER}/libcxx-${LLVM_VER}.src.tar.xz"
      LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VER}/libcxxabi-${LLVM_VER}.src.tar.xz"

      mkdir -p llvm-build llvm llvm/projects/libcxx llvm/projects/libcxxabi

      travis_retry wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm
      travis_retry wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx
      travis_retry wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi

      pushd llvm-build
      cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${DEPS} ../llvm
      cmake --build projects/libcxx --target install -- -j 2
      cmake --build projects/libcxxabi --target install -- -j 2
      popd

      export CXXFLAGS="${CXXFLAGS} -nostdinc++ -isystem ${DEPS}/include/c++/v1"
      export LDFLAGS="${LDFLAGS} -L${DEPS}/lib -lc++ -lc++abi"
      export LD_LIBRARY_PATH="${DEPS}/lib:${LD_LIBRARY_PATH}"
    fi
  # Install newer boost.
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update
      brew upgrade boost
    elif [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      mkdir -p ${DEPS}/include

      BOOST_URL="https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.gz"
      travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${DEPS}/include boost_1_68_0/boost
      CMAKE_OPTIONS+=" -DBOOST_ROOT=${DEPS}"
    fi

install:
  - mkdir build
  - pushd build
  - cmake ${CMAKE_OPTIONS} ..
  - COMPILE_TARGETS=($(cmake --build . --target help | grep -E "chart\.(binary_size|compile_time)\.${BENCHMARK}$" | cut -d " " -f 2 | sort))
  - EXECUTE_TARGETS=($(cmake --build . --target help | grep -E "execute\.${BENCHMARK}" | cut -d " " -f 2 | sort))
  - |
    for TARGET in ${COMPILE_TARGETS[@]} ${EXECUTE_TARGETS[@]}; do
      cmake --build . --target ${TARGET}
    done
  - popd

before_script:
  - git config --global user.name "Travis CI"
  - git config --global user.email "<>"
  - travis_retry git clone https://$GITHUB_TOKEN@github.com/mpark/variant --depth 1 --branch=gh-pages gh-pages &>/dev/null
  - |
    for COMPILE_TARGET in ${COMPILE_TARGETS[@]}; do
      category="$(echo ${COMPILE_TARGET} | cut -d '.' -f 2)"
      name="$(echo ${COMPILE_TARGET} | cut -d '.' -f 3-)"
      src="build/${name}"
      out="gh-pages/_${category}/${CC}/${name}"

      rm -rf ${out}
      mkdir -p ${out}

      # Add a YAML front matter to every chart (for Jekyll).
      {
        echo "---"
        echo "compiler: ${CC}"
        echo "timestamp: $(date '+%a, %-d %b %Y')"
        echo "---"
        cat ${src}/${category}.html
      } > ${out}/index.html
    done

script:
  - pushd gh-pages
  - git add --all .
  - git commit -m "Update benchmark '${BENCHMARK}' for '${CC}'."
  - travis_retry git pull --rebase && git push origin gh-pages &>/dev/null
  - popd

  - pushd build
  - ctest -R "execute\.${BENCHMARK}" -V
  - popd

notifications:
  email: false
