title: Variant Benchmark
email: mcypark@gmail.com
description: "A collection of `variant` benchmarks."
url: https://mpark.github.io/variant

collections:
  binary_size:
    name: Binary Size
    output: true
  compile_time:
    name: Compile Time
    output: true
    active: true
